apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-petsinternational-development
resources:
- ../../../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah dev"

images:
- name: twerthi/randomquotes
  newName: twerthi/randomquotes
  newTag: "2026.06.15.29"
#    newTag: "0.1.33"

# patches:
#  - target:
#     kind: Ingress
#     name: randomquotes-ingress-nginx  
#    path: randomquotes-ingress-nginx.yaml