apiVersion: v1
kind: Secret
metadata:
  name: {{ include "randomquotes.fullname" . }}-quotes-secrets
  labels:
  {{- include "randomquotes.labels" . | nindent 4 }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
  homepageDisplay: {{ required "quotesSecrets.homepageDisplay is required"
    .Values.quotesSecrets.homepageDisplay | b64enc | quote }}
type: Opaque
