apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-operator-randomquotes-pawsandclaws-test
  namespace: openshift-gitops
  annotations:
    argo.octopus.com/project: "openshift-gitops-operator-demo"
    argo.octopus.com/environment: "test"
    argo.octopus.com/tenant: "paws-and-claws"  
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/RandomQuotes-K8s.git
    targetRevision: HEAD
    path: k8s/overlays/tenants/pawsandclaws/test
  destination:
    server: https://kubernetes.default.svc
    namespace: randomquotes-pawsandclaws-test
  syncPolicy:
#    automated: 
#      prune: true
#      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true