apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-operator-randomquotes-purrfectpetshop-development
  namespace: openshift-gitops
  annotations:
    argo.octopus.com/project: "openshift-gitops-operator-demo"
    argo.octopus.com/environment: "development" 
    argo.octopus.com/tenant: "purrfect-pet-shop" 
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/RandomQuotes-K8s.git
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: randomquotes-purrfectpetshop-development
      valueFiles:
        - tenants/purrfectpetshop/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: randomquotes-purrfectpetshop-development
  syncPolicy:
#    automated: 
#      prune: true
#      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true