apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-operator-randomquotes-petsinternational-test
  namespace: openshift-gitops
  annotations:
    argo.octopus.com/project: "openshift-gitops-operator-demo"
    argo.octopus.com/environment: "test" 
    argo.octopus.com/tenant: "pets-international" 
    argo.octopus.com/image-replace-paths: "{{ .Values.quotesDeployment.randomquotesWeb.image.repository }}:{{ .Values.quotesDeployment.randomquotesWeb.image.tag }}"
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/RandomQuotes-K8s.git
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: randomquotes-petsinternational-test
      valueFiles:
        - tenants/petsinternational/test/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: randomquotes-petsinternational-test
  syncPolicy:
#    automated: 
#      prune: true
#      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true